title: Hussain Qadri
description: Projects, notes, and things I am working on

collections:
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "default"
