title: Hussain Qadri
description: Projects, notes, and things I am working on

markdown: kramdown
highlighter: rouge

collections:
  projects:
    output: true
  side_quests:
    output: true
    permalink: /side-quests/:path/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "side_quests"
    values:
      layout: "default"
